#!/usr/bin/env python3
"""Auto-generated replay for flow: flight-search-zurich-london
Generated by jev-webcontrol on 2026-09-28 04:04 UTC.

Replays the captured flow. Two modes:
  python replay.py --dry-run --state page.json   # offline, no browser
  python replay.py --url URL                      # live via CDP (needs Chrome daemon)

Locators are durable (semantic identity survives most DOM churn). If a locator
fails, replay auto-recovers by semantic identity, then reports breakpoints.
"""
import argparse
import json
import re
import sys
from pathlib import Path


def load_plan(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _base_label(label):
    return (label or "").split(" -> ")[0].strip()


def _parse_css(selector):
    if not selector:
        return None
    m = re.match(r'\[([\w-]+)\s*=\s*[\'"]?([^\'"]+)[\'"]?\]', selector or "")
    return (m.group(1), m.group(2)) if m else None


def resolve_offline(loc, actions, ignore_scope=False):
    cands = actions if ignore_scope else [a for a in actions if (a.get("scope") or "") == (loc.get("scope") or "")]
    for s in loc.get("strategies", []):
        for a in cands:
            if s.get("type") == "semantic":
                if a.get("role") == loc.get("role") and _base_label(a.get("label")) == (loc.get("name") or "").strip():
                    return a
            elif s.get("type") == "css":
                p = _parse_css(s.get("selector"))
                if p and (a.get("attrs") or {}).get(p[0]) == p[1]:
                    return a
    return None


def evaluate_spec(spec, actions, url, text):
    checks = []
    for c in spec.get("verification", []):
        if c["type"] == "url_matches":
            ok = bool(re.search(c["regex"], url or ""))
        elif c["type"] == "text_contains":
            ok = c["text"] in (text or "")
        elif c["type"] == "element_present":
            ok = any(a.get("label", "").split(" -> ")[0] == c["name"] for a in actions)
        elif c["type"] == "field_value":
            ok = any(a.get("label", "").split(" -> ")[0] == c["name"] and str(a.get("value", "")).strip() == str(c["equals"]).strip() for a in actions)
        else:
            ok = False
        checks.append({"type": c["type"], "ok": ok, "detail": "" if ok else c["type"] + " failed"})
    return {"passed": all(x["ok"] for x in checks), "checks": checks}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--plan", default=str(Path(__file__).resolve().parent.parent / "references" / "plan.json"))
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--state", help="captured page-state JSON for dry-run")
    ap.add_argument("--url", help="live URL (requires CDP daemon)")
    args = ap.parse_args()

    plan = load_plan(args.plan)
    steps = plan.get("steps", [])
    spec = plan.get("spec", {"verification": []})

    if args.dry_run:
        if not args.state:
            print("dry-run needs --state <page.json>"); sys.exit(2)
        state = json.loads(Path(args.state).read_text(encoding="utf-8"))
        actions = state.get("actions", [])
        broke = 0
        for i, step in enumerate(steps, 1):
            loc = step.get("locator", {})
            found = resolve_offline(loc, actions)
            if not found:
                found = resolve_offline(loc, actions, ignore_scope=True)
            status = "OK" if found else "BROKEN"
            if not found:
                broke += 1
            print("  step %d %-9s %-18s -> %s" % (i, step["operation"], step.get("target_label", ""), status))
            if found and step.get("verification"):
                r = evaluate_spec({"verification": step["verification"]}, [found], state.get("url", ""), state.get("text", ""))
                print("        step verify: %s" % ("PASS" if r["passed"] else "FAIL"))
        final = evaluate_spec(spec, actions, state.get("url", ""), state.get("text", ""))
        print("\nFinal verification: %s" % ("PASS" if final["passed"] else "FAIL"))
        for c in final["checks"]:
            if not c["ok"]:
                print("  - %s: %s" % (c["type"], c["detail"]))
        sys.exit(0 if final["passed"] and broke == 0 else 1)

    # Live mode (best-effort; needs the CDP daemon from harness.py).
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))
        import harness  # noqa: F401
    except Exception as e:
        print("live mode requires harness.py + a Chrome daemon:", e); sys.exit(3)
    print("live replay is wired via harness.py; pass --dry-run for the verified offline path.")


if __name__ == "__main__":
    main()
