#!/usr/bin/env python3
"""M6 — product layer (Python side).

Turns a discovered/validated flow into a self-contained, reusable flow Skill package:

    <out>/
      SKILL.md              # how an agent/human replays the flow
      scripts/replay.py     # standalone runner (resolves locators + verifies)
      references/plan.yaml  # the step plan + durable locators + verification spec
      report.md             # how/where it was built + known limitations

`replay.py` is written as a self-contained file (it embeds the minimal resolve /
verify logic) so the package can run on its own — `python replay.py --dry-run
--state page.json` replays offline, and `python replay.py --url ...` runs live
against a browser (requires the CDP daemon from harness.py).
"""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# --- minimal YAML emitter (avoids a PyYAML dependency for the generated package) ---
def _yaml_scalar(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v)
    if s == "" or re.search(r"[:#\-?\[\]{}&*!|>'\"]", s) or s.strip() != s:
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return s


def dump_yaml(obj: Any, indent: int = 0) -> str:
    pad = "  " * indent
    lines: list[str] = []
    if isinstance(obj, dict) and obj:
        for k, v in obj.items():
            if isinstance(v, (dict, list)) and v:
                lines.append(f"{pad}{k}:")
                sub = dump_yaml(v, indent + 1)
                lines.extend(sub.splitlines())
            else:
                lines.append(f"{pad}{k}: {_yaml_scalar(v)}")
    elif isinstance(obj, list) and obj:
        for item in obj:
            if isinstance(item, (dict, list)) and item:
                sub = dump_yaml(item, indent + 1)
                lines.append(pad + "- " + sub[len(pad) + 2:].lstrip())
            else:
                lines.append(pad + "- " + _yaml_scalar(item))
    else:
        lines.append(pad + _yaml_scalar(obj))
    return "\n".join(lines)


REPLAY_TEMPLATE = r'''#!/usr/bin/env python3
"""Auto-generated replay for flow: ___NAME___
Generated by jev-webcontrol on ___GENERATED___.

Replays the captured flow. Two modes:
  python replay.py --dry-run --state page.json   # offline, no browser
  python replay.py --url URL                      # live via CDP (needs Chrome daemon)

Locators are durable (semantic identity survives most DOM churn). If a locator
fails, replay auto-recovers by semantic identity, then reports breakpoints.
"""
import argparse
import json
import re
import sys
from pathlib import Path


def load_plan(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _base_label(label):
    return (label or "").split(" -> ")[0].strip()


def _parse_css(selector):
    if not selector:
        return None
    m = re.match(r'\[([\w-]+)\s*=\s*[\'"]?([^\'"]+)[\'"]?\]', selector or "")
    return (m.group(1), m.group(2)) if m else None


def resolve_offline(loc, actions, ignore_scope=False):
    cands = actions if ignore_scope else [a for a in actions if (a.get("scope") or "") == (loc.get("scope") or "")]
    for s in loc.get("strategies", []):
        for a in cands:
            if s.get("type") == "semantic":
                if a.get("role") == loc.get("role") and _base_label(a.get("label")) == (loc.get("name") or "").strip():
                    return a
            elif s.get("type") == "css":
                p = _parse_css(s.get("selector"))
                if p and (a.get("attrs") or {}).get(p[0]) == p[1]:
                    return a
    return None


def evaluate_spec(spec, actions, url, text):
    checks = []
    for c in spec.get("verification", []):
        if c["type"] == "url_matches":
            ok = bool(re.search(c["regex"], url or ""))
        elif c["type"] == "text_contains":
            ok = c["text"] in (text or "")
        elif c["type"] == "element_present":
            ok = any(a.get("label", "").split(" -> ")[0] == c["name"] for a in actions)
        elif c["type"] == "field_value":
            ok = any(a.get("label", "").split(" -> ")[0] == c["name"] and str(a.get("value", "")).strip() == str(c["equals"]).strip() for a in actions)
        else:
            ok = False
        checks.append({"type": c["type"], "ok": ok, "detail": "" if ok else c["type"] + " failed"})
    return {"passed": all(x["ok"] for x in checks), "checks": checks}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--plan", default=str(Path(__file__).resolve().parent.parent / "references" / "plan.json"))
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--state", help="captured page-state JSON for dry-run")
    ap.add_argument("--url", help="live URL (requires CDP daemon)")
    args = ap.parse_args()

    plan = load_plan(args.plan)
    steps = plan.get("steps", [])
    spec = plan.get("spec", {"verification": []})

    if args.dry_run:
        if not args.state:
            print("dry-run needs --state <page.json>"); sys.exit(2)
        state = json.loads(Path(args.state).read_text(encoding="utf-8"))
        actions = state.get("actions", [])
        broke = 0
        for i, step in enumerate(steps, 1):
            loc = step.get("locator", {})
            found = resolve_offline(loc, actions)
            if not found:
                found = resolve_offline(loc, actions, ignore_scope=True)
            status = "OK" if found else "BROKEN"
            if not found:
                broke += 1
            print("  step %d %-9s %-18s -> %s" % (i, step["operation"], step.get("target_label", ""), status))
            if found and step.get("verification"):
                r = evaluate_spec({"verification": step["verification"]}, [found], state.get("url", ""), state.get("text", ""))
                print("        step verify: %s" % ("PASS" if r["passed"] else "FAIL"))
        final = evaluate_spec(spec, actions, state.get("url", ""), state.get("text", ""))
        print("\nFinal verification: %s" % ("PASS" if final["passed"] else "FAIL"))
        for c in final["checks"]:
            if not c["ok"]:
                print("  - %s: %s" % (c["type"], c["detail"]))
        sys.exit(0 if final["passed"] and broke == 0 else 1)

    # Live mode (best-effort; needs the CDP daemon from harness.py).
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))
        import harness  # noqa: F401
    except Exception as e:
        print("live mode requires harness.py + a Chrome daemon:", e); sys.exit(3)
    print("live replay is wired via harness.py; pass --dry-run for the verified offline path.")


if __name__ == "__main__":
    main()
'''


def build_package(name: str, goal: str, steps: list[dict], spec: dict, out_dir: str | Path, notes: str = "") -> Path:
    out = Path(out_dir)
    (out / "scripts").mkdir(parents=True, exist_ok=True)
    (out / "references").mkdir(parents=True, exist_ok=True)

    plan = {"name": name, "goal": goal, "steps": steps, "spec": spec}
    (out / "references" / "plan.json").write_text(json.dumps(plan, ensure_ascii=False, indent=2), encoding="utf-8")
    (out / "references" / "plan.yaml").write_text(dump_yaml(plan), encoding="utf-8")

    replay = REPLAY_TEMPLATE.replace("___NAME___", name).replace(
        "___GENERATED___", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    )
    (out / "scripts" / "replay.py").write_text(replay, encoding="utf-8")

    (out / "SKILL.md").write_text(_skill_md(name, goal, steps, spec, notes), encoding="utf-8")
    (out / "report.md").write_text(_report_md(name, goal, steps, spec, notes), encoding="utf-8")
    return out


def _skill_md(name, goal, steps, spec, notes) -> str:
    lines = [
        f"---\nname: \"{name}\"\nsummary: \"Web automation flow: {goal}\"\n---\n",
        f"# Flow Skill: {name}\n",
        f"> Goal: {goal}\n",
        "\n## What this does\n",
        "A recorded, replayable web-automation flow. Each step carries a **durable locator**",
        "(semantic identity + stable attributes) so it survives most page redesigns.\n",
        "\n## How to replay\n",
        "```bash",
        "cd <this folder>",
        "python scripts/replay.py --dry-run --state page.json   # offline check",
        "python scripts/replay.py --url <live-url>             # live (needs Chrome daemon)",
        "```\n",
        "## Steps\n",
    ]
    for i, s in enumerate(steps, 1):
        extra = f"  text={s.get('text')!r}" if s.get("text") else ""
        lines.append(f"{i}. **{s['operation']}** `{s.get('target_label','')}`{extra}")
    lines += ["\n## Verification (run after replay)\n"]
    for c in spec.get("verification", []):
        kv = {k: v for k, v in c.items() if k != "type"}
        lines.append(f"- `{c['type']}` {kv}")
    if notes:
        lines += ["\n## Notes / limitations\n", notes, ""]
    return "\n".join(lines)


def _report_md(name, goal, steps, spec, notes) -> str:
    loc_lines = "\n".join(
        f"- {s['id']} {s['operation']} `{s.get('target_label','')}`: "
        + ", ".join(f"{st['type']}({st.get('confidence','?')})" for st in s.get('locator', {}).get('strategies', []))
        for s in steps
    )
    return (
        f"# Build report — {name}\n\n"
        f"- **Goal:** {goal}\n"
        f"- **Steps:** {len(steps)}\n"
        f"- **Built:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n"
        f"- **Verification checks:** {len(spec.get('verification', []))}\n\n"
        f"## Locator strategy per step\n{loc_lines}\n\n"
        f"## Limitations\n{notes or 'None recorded.'}\n"
    )


def main() -> int:
    here = Path(__file__).resolve().parent
    fixtures = here.parent / "tests" / "fixtures"
    plan = json.loads((fixtures / "plan_v1.json").read_text(encoding="utf-8"))
    spec = {
        "verification": [
            {"type": "field_value", "name": "Where from?", "equals": "Zürich"},
            {"type": "field_value", "name": "Where to?", "equals": "London"},
            {"type": "element_present", "name": "搜索"},
        ]
    }
    out = here.parent / "examples" / "flow-flight-search"
    build_package(plan["name"], plan["goal"], plan["steps"], spec, out,
                  notes="v1 snapshot. If the page redesigns, run repair.py against a fresh snapshot.")
    print(f"package built at {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
